### ISSUE TITLE
On latest Divi, Maps API JS is falsely prevented from printing 

### ISSUE THREAD

**Issue by mathetos** [impress-org/google-maps-builder#206] opened 2016-07-13 22:24 UTC
On version 2.7.8 of the Divi theme, our functions which check for other enqueued scripts are falsely being triggered, which prevents the Maps API script from printing on the page and thus the map from appearing correctly at all.
## Replication Steps
- Instead 2.7.8 of Divi
- Install either FREE or PRO of Maps Builder
- Configure the Maps API Key ONLY in Maps Builder (Divi has it's own settings, but leave them blank)
- Create a map. In the backend the map will appear just fine.
- Publish the map, and view and it will be blank.
- Go to `includes\class-gmb-scripts.php` in FREE, to line 137 and remove the IF statement around `$this->load_maps_api`. Save and view the map again and it will appear correctly.

**Comment by beneppard** [comment] 2016-09-07 14:56
@mathetos – I'm trying to deal with this same issue, and I'm not well versed in PHP. Here is the PHP on line 137:

`function print_gmap_footer() {
		if ($load_maps_api) {
			wp_print_scripts( 'google-maps-builder-gmaps' );
		}
		wp_print_scripts( 'google-maps-builder-plugin-script' );
		wp_print_scripts( 'google-maps-builder-maps-icons' );
	}`

What did you do to get it to work? Really appreciate you posting.

**Comment by mathetos** [comment] 2016-09-08 16:08
Hi @beneppard You should change that line to the following:

```
function print_gmap_footer() { 
    wp_print_scripts( 'google-maps-builder-gmaps' );
    wp_print_scripts( 'google-maps-builder-plugin-script' ); 
    wp_print_scripts( 'google-maps-builder-maps-icons' ); 
}
```

**Comment by darrenkeoughball** [comment] 2016-09-10 15:33
Hi I have the same issue with Divi. 

When you say: Go to includes\class-gmb-scripts.php in FREE, to line 137 and remove the IF statement around $this->load_maps_api. Save and view the map again and it will appear correctly.
Where exactly do I go to make this edit? What file where and how do I access it? 

Thank you!
Darren

**Comment by beneppard** [comment] 2016-09-10 15:38
When download and unzip the plugin, you should see a folder insider called includes containing the class.gmb.scripts.php file. On line 137 you replace:

`function print_gmap_footer() { if ($load_maps_api) { wp_print_scripts( 'google-maps-builder-gmaps' ); } wp_print_scripts( 'google-maps-builder-plugin-script' ); wp_print_scripts( 'google-maps-builder-maps-icons' ); }`

with 

`function print_gmap_footer() { 
    wp_print_scripts( 'google-maps-builder-gmaps' );
    wp_print_scripts( 'google-maps-builder-plugin-script' ); 
    wp_print_scripts( 'google-maps-builder-maps-icons' ); 
}`

If you save the file and reupload the plugin it should work. Keep in mind that a plugin update will wipe out this fix, but it will solve the problem short term.

**Comment by darrenkeoughball** [comment] 2016-09-10 15:40
Thank so much for the quick reply. If I edit the plugin and upload it again will I lose all of my map markers? 

Get Outlook for iOS




On Sat, Sep 10, 2016 at 4:38 PM +0100, "beneppard" <notifications@github.com> wrote:












When download and unzip the plugin, you should see a folder insider called includes containing the class.gmb.scripts.php file. On line 137 you replace:



function print_gmap_footer() { if ($load_maps_api) { wp_print_scripts( 'google-maps-builder-gmaps' ); } wp_print_scripts( 'google-maps-builder-plugin-script' ); wp_print_scripts( 'google-maps-builder-maps-icons' ); }



with 



function print_gmap_footer() { 

    wp_print_scripts( 'google-maps-builder-gmaps' );

    wp_print_scripts( 'google-maps-builder-plugin-script' ); 

    wp_print_scripts( 'google-maps-builder-maps-icons' ); 

}



If you save the file and reupload the plugin it should work. Keep in mind that a plugin update will wipe out this fix, but it will solve the problem short term.

**Comment by beneppard** [comment] 2016-09-10 15:47
As long as you don't delete the plugin, Wordpress should continue to store your maps in the database.

If it was me, I would connect via FTP, navigate to where this one file is you've changed, and just upload that one file.

**Comment by darrenkeoughball** [comment] 2016-09-10 22:06
Thank you that worked!

**Comment by mathetos** [comment] 2016-09-26 18:52
We need to figure out why our duplicate maps JS check function is trigerring falsely for Divi. I have a feeling they are registering it, but only enqueuing on relevant pages. Hmmm...

**Comment by nishitlangaliya** [comment] 2018-10-01 05:36
@DevinWalker ,

I have gone through the steps to reproduce the issue but unable to reproduce issue. I have prepared the video of my testing please review it and let me know if I am missing anything here.

https://www.useloom.com/share/95aae8dc91274e12b30c9ec595d36b23

Thanks

**Comment by kevinwhoffman** [comment] 2018-10-02 05:51
Per discussion with @nishitlangaliya, this issue can no longer be reproduced. Closing.

**Closed by kevinwhoffman** 2018-10-02 05:51 UTC
Labels: needs-dev-feedback
